<a href="https://colab.research.google.com/github/stali1234/python/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [7]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
a =     np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a = np.full((3,2),5)
print(a)

[[5 5]
 [5 5]
 [5 5]]


In [16]:
#identity matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
#
randommatrix = np.random.random((2,3))
print(randommatrix)
randommatrix[1,1:] =1
print(randommatrix)

[[0.32207143 0.73073363 0.81501693]
 [0.79592389 0.35086662 0.69743913]]
[[0.32207143 0.73073363 0.81501693]
 [0.79592389 1.         1.        ]]


In [30]:
z = np.zeros((3,3))
print(z)
z[1, :] = 5
print(z)
z[:,-1] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [32]:
print(z.dtype)

float64


In [36]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [39]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [41]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [43]:
#multpplication of vectors
a = np.array([1,2,3,4,5])
b= np.array([1,2,3,4,5])
print(a.dot(b))


55


In [45]:
print(sum(a))

15


In [49]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0))

[5 7 9]


In [60]:
a = np.array([1,2,3])
print(a)
b = np.array([1,2,3])
b = b**2
print(b)
c = np.stack((a,b),axis=0)

[1 2 3]
[1 4 9]


In [67]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [72]:
np.random.shuffle(a)
print(a)

[ 7 10 13 14 11 12  8  5  6  9]


In [75]:
#returns values from a standard normal distribution

a = np.random.randn(2,3)
print(a)
element = np.random.choice([1,2,3,4,56,4])
print(element)

[[ 0.75712947 -0.08060649  0.52546641]
 [-0.05583352  0.7299492   0.94271607]]
4


In [76]:

##some more numpy functions - staticst
#min max
#mean
#median
#average
#variance
#standard devidation

In [80]:
a = np.array([[1,2,3,4],[5,6,7,87]])
print(a)
#specify axis for the direction in case of mulidim array
print(np.min(a))
print(np.max(a,axis=0))
#mean average all the elements


[[ 1  2  3  4]
 [ 5  6  7 87]]
1
[ 5  6  7 87]


In [82]:
a = np.array([1,2,3,4,4])
m = sum(a)/5
print(m)


2.8


In [84]:
c =  np.array([1,2,3,4,5])
print(np.median(c))

3.0
